version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    container_name: mysql-docker
    environment:
      MYSQL_DATABASE: 'n2g-db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - n2g-database:/var/lib/mysql

  app: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-docker
    restart: always  
    env_file:
      - ./.env
    environment:
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3001:3001'
    depends_on:
      - db   

volumes:
  n2g-database:
  n2g-express:
