version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: postgres-docker
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5433:5432'
    networks:
      - n2g-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-docker
    restart: always
    env_file:
      - ./.env
    environment:
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3001:3001'
    depends_on:
      - db
    networks:
      - n2g-network
    volumes:
      - n2g-database:/app/db

networks:
  n2g-network:

volumes:
  postgres-data:
  n2g-database:
